name: Build ZMK firmware
on:
  push:
    paths-ignore:
      - "mod/**"
  pull_request:
    paths-ignore:
      - "mod/**"
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
